services:
  db:
    container_name: url-shortener-db
    image: postgres:latest
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - url-shortener-network
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    container_name: url-shortener-server
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file:
      - .env
    networks:
      - url-shortener-network
    depends_on:
      db:
        condition: service_started
    links:
      - db

volumes:
  db-data:

networks:
  url-shortener-network:
    driver: bridge